CREATE DATABASE IF NOT EXISTS `seg`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `seg`;

CREATE TABLE IF NOT EXISTS `escuelas` (
  `CCT` VARCHAR(50) NOT NULL PRIMARY KEY,
  `NOMBRECT` VARCHAR(255) NOT NULL,
  `NOMBREMUN` VARCHAR(255) NULL,
  `NOMBRELOC` VARCHAR(255) NULL,
  `STATUS` VARCHAR(20) NULL,
  `SUBNIVEL` VARCHAR(100) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `cfe_precarga` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `RPU` VARCHAR(20) NOT NULL,
  `nombre_cfe` VARCHAR(255) NULL,
  `poblacion_cfe` VARCHAR(255) NULL,
  `tarifa_cfe` VARCHAR(10) NULL,
  `periodo_vence` DATE NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `escuelas_rpu` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `CCT` VARCHAR(50) NOT NULL,
  `RPU` VARCHAR(20) NOT NULL UNIQUE,
  `nombre_recibo_cfe` VARCHAR(255) NULL,
  `poblacion_cfe` VARCHAR(255) NULL,
  `tarifa_cfe` VARCHAR(10) NULL,
  FOREIGN KEY (`CCT`) REFERENCES `escuelas`(`CCT`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
