CREATE TABLE IF NOT EXISTS `cfe_precarga` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `RPU` VARCHAR(20) NOT NULL,
  `nombre_cfe` VARCHAR(255) NULL,
  `poblacion_cfe` VARCHAR(255) NULL,
  `tarifa_cfe` VARCHAR(10) NULL,
  `periodo_vence` DATE NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `escuelas_rpu` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `CCT` VARCHAR(50) NOT NULL,
  `RPU` VARCHAR(20) NOT NULL UNIQUE,
  `nombre_recibo_cfe` VARCHAR(255) NULL,
  FOREIGN KEY (`CCT`) REFERENCES `escuelas`(`CCT`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
